# Woodpecker CI Configuration for Codeberg
# Place this file at .woodpecker.yml in repository root

pipeline:
  # Main test suite on Node 20
  test-main:
    image: node:20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "Running tests..."
      - npm test
    when:
      event: [push, pull_request]

  # Test on Node 18 (minimum supported)
  test-node-18:
    image: node:18
    commands:
      - npm ci
      - npm run test:unit
    when:
      event: [push, pull_request]

  # Test on Node 21 (latest)
  test-node-21:
    image: node:21
    commands:
      - npm ci
      - npm run test:unit
    when:
      event: [push, pull_request]

  # Integration tests (separate for better visibility)
  test-integration:
    image: node:20
    commands:
      - npm ci
      - npm run test:integration
    when:
      event: [push, pull_request]

  # Rust build
  rust-build:
    image: rust:latest
    commands:
      - cd rust
      - cargo build --verbose
      - cargo test --verbose
    when:
      event: [push, pull_request]

  # Security audit
  security:
    image: node:20
    commands:
      - npm audit --audit-level=moderate
    when:
      event: [push, pull_request]
    failure: ignore  # Don't fail build on audit issues

  # Syntax check
  lint:
    image: node:20
    commands:
      - node --check src/*.js
      - node --check test/*.js
    when:
      event: [push, pull_request]
